const actions = {
  FETCH_VEHICLES_REQUEST: 'FETCH_VEHICLES_REQUEST',
  ADD_VEHICLE_REQUEST: 'ADD_VEHICLE_REQUEST',
  REMOVE_VEHICLE_REQUEST: 'REMOVE_VEHICLE_REQUEST',
  FETCH_VEHICLES_SUCCESS: 'FETCH_VEHICLES_SUCCESS',
  ADD_VEHICLE_SUCCESS: 'ADD_VEHICLE_SUCCESS',
  REMOVE_VEHICLE_SUCCESS: 'REMOVE_VEHICLE_SUCCESS',
  FETCH_VEHICLES_FAILURE: 'FETCH_VEHICLES_FAILURE',
  ADD_VEHICLE_FAILURE: 'ADD_VEHICLE_FAILURE',
  REMOVE_VEHICLE_FAILURE: 'REMOVE_VEHICLE_FAILURE',
  SEARCH: 'SEARCH',
};
export default actions;
