const actions = {
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  
  ADD_VEHICLE_REQUEST: 'ADD_VEHICLE_REQUEST',
  ADD_VEHICLE_SUCCESS: 'ADD_VEHICLE_SUCCESS',
  ADD_VEHICLE_FAILURE: 'ADD_VEHICLE_FAILURE',
  
  REMOVE_VEHICLE_REQUEST: 'REMOVE_VEHICLE_REQUEST',
  REMOVE_VEHICLE_SUCCESS: 'REMOVE_VEHICLE_SUCCESS',
  REMOVE_VEHICLE_FAILURE: 'REMOVE_VEHICLE_FAILURE',
  
  FETCH_VEHICLES_FAILURE: 'FETCH_VEHICLES_FAILURE',
  FETCH_VEHICLES_REQUEST: 'FETCH_VEHICLES_REQUEST',
  FETCH_VEHICLES_SUCCESS: 'FETCH_VEHICLES_SUCCESS',
  
  SEARCH_VEHICLES_SUCCESS: 'SEARCH_VEHICLEs_SUCCESS',
  SEARCH_VEHICLES_FAILURE: 'SEARCH_VEHICLEs_FAILURE',
  SEARCH_VEHICLES_REQUEST: 'SEARCH_VEHICLES_REQUEST',
};
export default actions;
